## Table of Contents
#### 1. Importing libraries and Data
#### 2. Data Wrangling
##### 2.1. Dropping Columns
##### 2.2. Changing Data Types
##### 2.3. Transposing Data
#### 3. Data Dictionary
#### 4. Subsetting
#### 5. Task 4.4

## 01. Importing libraries and Data

In [2]:
# Import libraries
import pandas as pd
import numpy as np
import os

In [3]:
# Main path
path = r'/Users/helenarobalinho/Desktop/Data Analytics/2. Data Immersion/Achievement 4 - Python Fundamentals for Data Analysts/03-2026 Instacart Basket Analysis'

In [4]:
# Import orders.csv and products.csv datasets
df_orders = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'orders.csv'), index_col = False)
df_products = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'products.csv'), index_col = False)

## 02. Data Wrangling

### 2.1. Dropping Columns

In [48]:
# Dropping eval_set column from orders.csv
df_orders.drop(columns = ['eval_set'])

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0
...,...,...,...,...,...,...
3421078,2266710,206209,10,5,18,29.0
3421079,1854736,206209,11,4,10,30.0
3421080,626363,206209,12,1,12,18.0
3421081,2977660,206209,13,1,12,7.0
3421082,272231,206209,14,6,14,30.0

#### Renaming Columns

In [49]:
# Renaming the 'order_dow' column to 'orders_day_of_week'
df_orders.rename(columns = {'order_dow' : 'orders_day_of_week'}, inplace = True)

In [50]:
df_orders.head()

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

### 2.2. Changing Data Types

In [8]:
df_orders.describe ()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
count,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.214874e+06
mean,1.710542e+06,1.029782e+05,1.715486e+01,2.776219e+00,1.345202e+01,1.111484e+01
std,9.875817e+05,5.953372e+04,1.773316e+01,2.046829e+00,4.226088e+00,9.206737e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.552715e+05,5.139400e+04,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.710542e+06,1.026890e+05,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00
75%,2.565812e+06,1.543850e+05,2.300000e+01,5.000000e+00,1.600000e+01,1.500000e+01
max,3.421083e+06,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01

In [9]:
# Changing the data type of the "order_id" column from a number to a string 
df_orders ['order_id'] = df_orders ['order_id'].astype ('str')

In [10]:
df_orders ['order_id'].dtype

dtype('O')

### 2.3 Transposing Data

In [11]:
# Importing data set departments.csv
df_dep = pd.read_csv (os.path.join (path, '02 Data', 'Original Data', 'departments.csv'), index_col = False)

In [12]:
df_dep.head()

,department_id,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,department,frozen,other,bakery,produce,alcohol,international,beverages,pets,dry goods pasta,...,meat seafood,pantry,breakfast,canned goods,dairy eggs,household,babies,snacks,deli,missing

In [13]:
# Transpose
df_dep.T

                             0
department_id       department
1                       frozen
2                        other
3                       bakery
4                      produce
5                      alcohol
6                international
7                    beverages
8                         pets
9              dry goods pasta
10                        bulk
11               personal care
12                meat seafood
13                      pantry
14                   breakfast
15                canned goods
16                  dairy eggs
17                   household
18                      babies
19                      snacks
20                        deli
21                     missing

In [14]:
# creating a new dataframe 'df_dep_t' from the transposed version 
df_dep_t = df_dep.T

In [15]:
df_dep_t

                             0
department_id       department
1                       frozen
2                        other
3                       bakery
4                      produce
5                      alcohol
6                international
7                    beverages
8                         pets
9              dry goods pasta
10                        bulk
11               personal care
12                meat seafood
13                      pantry
14                   breakfast
15                canned goods
16                  dairy eggs
17                   household
18                      babies
19                      snacks
20                        deli
21                     missing

In [16]:
# adding an index 
df_dep_t. reset_index ()

            index                0
0   department_id       department
1               1           frozen
2               2            other
3               3           bakery
4               4          produce
5               5          alcohol
6               6    international
7               7        beverages
8               8             pets
9               9  dry goods pasta
10             10             bulk
11             11    personal care
12             12     meat seafood
13             13           pantry
14             14        breakfast
15             15     canned goods
16             16       dairy eggs
17             17        household
18             18           babies
19             19           snacks
20             20             deli
21             21          missing

#### 1. Create a new header

In [17]:
# Take the first row of df_dep_t for the header
new_header = df_dep_t.iloc [0]

In [18]:
new_header

0    department
Name: department_id, dtype: object

#### 2. Remove the first row in the dataframe

In [19]:
# create a new dataframe that only copies rows beyond the first row
df_dep_t_new = df_dep_t[1:]

In [20]:
df_dep_t_new

                  0
1            frozen
2             other
3            bakery
4           produce
5           alcohol
6     international
7         beverages
8              pets
9   dry goods pasta
10             bulk
11    personal care
12     meat seafood
13           pantry
14        breakfast
15     canned goods
16       dairy eggs
17        household
18           babies
19           snacks
20             deli
21          missing

#### 3. Add the new header

In [21]:
# set the header row as your new header
df_dep_t_new.columns = new_header

In [22]:
df_dep_t_new

department_id       department
1                       frozen
2                        other
3                       bakery
4                      produce
5                      alcohol
6                international
7                    beverages
8                         pets
9              dry goods pasta
10                        bulk
11               personal care
12                meat seafood
13                      pantry
14                   breakfast
15                canned goods
16                  dairy eggs
17                   household
18                      babies
19                      snacks
20                        deli
21                     missing

## 3. Data Dictionary

In [23]:
# create a data dictionary that contains meanings for the values in the "department_id" column
data_dict = df_dep_t_new.to_dict('index')

In [24]:
data_dict

{'1': {'department': 'frozen'},
 '2': {'department': 'other'},
 '3': {'department': 'bakery'},
 '4': {'department': 'produce'},
 '5': {'department': 'alcohol'},
 '6': {'department': 'international'},
 '7': {'department': 'beverages'},
 '8': {'department': 'pets'},
 '9': {'department': 'dry goods pasta'},
 '10': {'department': 'bulk'},
 '11': {'department': 'personal care'},
 '12': {'department': 'meat seafood'},
 '13': {'department': 'pantry'},
 '14': {'department': 'breakfast'},
 '15': {'department': 'canned goods'},
 '16': {'department': 'dairy eggs'},
 '17': {'department': 'household'},
 '18': {'department': 'babies'},
 '19': {'department': 'snacks'},
 '20': {'department': 'deli'},
 '21': {'department': 'missing'}}

In [25]:
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [26]:
# Use the data dictionary to determine what "Row O has a "department_id" of 19" stands for
print (data_dict.get('19'))

{'department': 'snacks'}

## 4. Subsetting

In [27]:
# creating a subset for df_products dataframe that only contains the snacks department
df_snacks = df_products [df_products['department_id']==19]

In [28]:
df_snacks.head ()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
15,16,Mint Chocolate Flavored Syrup,103,19,5.2
24,25,Salted Caramel Lean Protein & Fiber Bar,3,19,1.9
31,32,Nacho Cheese White Bean Chips,107,19,4.9
40,41,Organic Sourdough Einkorn Crackers Rosemary,78,19,6.5

In [29]:
# Method 2 with the function loc and ==
df_snacks_2 = df_products. loc[df_products ['department_id'] == 19]

In [30]:
# Method 3 with the function loc and isin
df_snacks_3 = df_products. loc[df_products ['department_id']. isin( [19])]

## 5. Task 4.4

### 5.1 Find another identifier variable in the df_ords as a numeric variable and change it to a suitable format.

In [31]:
# Changing the data type of the "user_id" column from a number to a string 
df_orders ['user_id'] = df_orders ['user_id'].astype ('str')

In [32]:
df_orders ['order_id'].dtype

dtype('O')

### 5.2 Look for a variable in your df_ords dataframe with an unintuitive name and change its name without overwriting the dataframe

In [33]:
df_orders_new = df_orders.rename(columns = {'order_hour_of_day' : 'order_hour'})

In [34]:
df_orders_new.head()

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

### 5.3 Your client wants to know what the busiest hour is for placing orders. Find the frequency of the corresponding variable and share your findings

In [35]:
df_orders_new ['order_hour'].value_counts (dropna = False)

order_hour
10    288418
11    284728
15    283639
14    283042
13    277999
12    272841
16    272553
9     257812
17    228795
18    182912
8     178201
19    140569
20    104292
7      91868
21     78109
22     61468
23     40043
6      30529
0      22758
1      12398
5       9569
2       7539
4       5527
3       5474
Name: count, dtype: int64

#### The busiest hour is 10h

### 5.4 Determine the meaning behind a value of 4 in the "department_id" column within the df_prods using a data dictionary.

In [36]:
print (data_dict.get ('4'))

{'department': 'produce'}

#### It means the department is Produce

### 5.5 The sales team in your client's organization wants to know more about breakfast item sales. Create a subset containing only the required information

In [37]:
# In the data dictionary, breakfast items belong to the department_id = 14
df_breakfast = df_products [df_products ['department_id']==14]

In [38]:
df_breakfast.head()

,product_id,product_name,aisle_id,department_id,prices
27,28,Wheat Chex Cereal,121,14,10.1
33,34,NaN,121,14,12.2
67,68,"Pancake Mix, Buttermilk",130,14,13.7
89,90,Smorz Cereal,121,14,3.9
210,211,Gluten Free Organic Cereal Coconut Maple Vanilla,130,14,3.6

### 5.6 They'd also like to see details about products that customers might use to throw dinner parties. Your task is to find all observations from the entire dataframe that include items from the following departments: alcohol, deli, beverages, and meat/seafood. You'll need to present this subset to your client

In [39]:
# In the data dictionary:
# alcohol items belong to the department_id = 5
# deli items belong to the department_id = 20
# beverages items belong to the department_id = 7
# meat/seafood items belong to the department_id = 12

df_dinner_party = df_products.loc [df_products['department_id'].isin ([5, 20, 7, 12])]

In [40]:
df_dinner_party.head()

,product_id,product_name,aisle_id,department_id,prices
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
6,7,Pure Coconut Water With Orange,98,7,4.4
9,10,Sparkling Orange Juice & Prickly Pear Beverage,115,7,8.4
10,11,Peach Mango Juice,31,7,2.8
16,17,Rendered Duck Fat,35,12,17.1

- How many rows does the last dataframe you created have?

In [41]:
df_dinner_party.shape

(7650, 5)

In [42]:
# It has 7650 rows

### 5.7 Extract all the information you can about the customer with a "user_id" of "1."

In [43]:
# set a data frame for user_id 1
df_user1=df_orders.loc[df_orders['user_id'] == '1']

In [44]:
# See the data
df_user1

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
5,3367565,1,prior,6,2,7,19.0
6,550135,1,prior,7,1,9,20.0
7,3108588,1,prior,8,1,14,14.0
8,2295261,1,prior,9,1,16,0.0
9,2550362,1,prior,10,4,8,30.0
10,1187899,1,train,11,4,8,14.0

### 5.8 What basic stats can you provide about this user?

In [45]:
df_user1.describe()

,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
count,11.000000,11.000000,11.000000,10.000000
mean,6.000000,2.636364,10.090909,19.000000
std,3.316625,1.286291,3.477198,9.030811
min,1.000000,1.000000,7.000000,0.000000
25%,3.500000,1.500000,7.500000,14.250000
50%,6.000000,3.000000,8.000000,19.500000
75%,8.500000,4.000000,13.000000,26.250000
max,11.000000,4.000000,16.000000,30.000000

#### This user places orders at the start of the week, and usually will order before 12pm.
#### The average mean time between placing orders is 19 days.

## Exporting df_ords dataframe as "orders_wrangled.csv" in "Prepared Data" folder

In [46]:
df_orders.to_csv(os.path.join(path, '02 Data','Prepared Data', 'orders_wrangled.csv'))

## Exporting the df_dep_t_new dataframe as "departments_wrangled.csv" in "Prepared Data"

In [47]:
df_dep_t_new.to_csv(os.path.join(path, '02 Data','Prepared Data', 'departments_wrangled.csv'))