# 4.6.2 Combining and Exporting Data

## Table of Contents
#### 1. Importing libraries and Data
#### 2. Merging orders and products dataframes

## 1. Importing libraries and Data

In [2]:
# Import libraries

import pandas as pd
import numpy as np
import os

In [3]:
# Main path
path = r'/Users/helenarobalinho/Desktop/Data Analytics/2. Data Immersion/Achievement 4 - Python Fundamentals for Data Analysts/03-2026 Instacart Basket Analysis'

In [4]:
# Import the orders_products_combined df from the pickle file
orders_products_combined = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_combined.pkl'))

In [5]:
# Check the output
orders_products_combined.head()

,Unnamed: 0.1,Unnamed: 0,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,First_order,product_id,add_to_cart_order,reordered,_merge
0,0,0,2539329,1,prior,1,2,8,NaN,True,196,1,0,both
1,0,0,2539329,1,prior,1,2,8,NaN,True,14084,2,0,both
2,0,0,2539329,1,prior,1,2,8,NaN,True,12427,3,0,both
3,0,0,2539329,1,prior,1,2,8,NaN,True,26088,4,0,both
4,0,0,2539329,1,prior,1,2,8,NaN,True,26405,5,0,both

In [6]:
# Check the shape of the imported dataframe
orders_products_combined.shape
# The shape is still the same

(32434489, 14)

In [7]:
# Import the products df from prepared data file
df_products_checked = pd.read_csv(os.path.join(path, '02 Data','Prepared Data', 'products_checked.csv'),index_col=0)

In [8]:
# Checking the output
df_products_checked.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [9]:
# Checking the shape of the products dataframe
df_products_checked.shape

(49672, 5)

In [10]:
# Checking the shape of the orders_products_combined dataframe again
orders_products_combined.shape

(32434489, 14)

## 2. Merging orders and products dataframes

#### Observation: the most suitable way to merge the two dataframes is to use the product_id column. An inner join would be the best course of action since the information that is presented wouldn't aid in a better understanding in both dataframes.

In [11]:
# Test the merge without overwriting:
pd.merge(orders_products_combined, df_products_checked, on = ['product_id'], indicator = 'Match')

,Unnamed: 0.1,Unnamed: 0,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,First_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,Match
0,0,0,2539329,1,prior,1,2,8,NaN,True,196,1,0,both,Soda,77,7,9.0,both
1,0,0,2539329,1,prior,1,2,8,NaN,True,14084,2,0,both,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both
2,0,0,2539329,1,prior,1,2,8,NaN,True,12427,3,0,both,Original Beef Jerky,23,19,4.4,both
3,0,0,2539329,1,prior,1,2,8,NaN,True,26088,4,0,both,Aged White Cheddar Popcorn,23,19,4.7,both
4,0,0,2539329,1,prior,1,2,8,NaN,True,26405,5,0,both,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32404854,3421081,3421081,2977660,206209,prior,13,1,12,7.0,False,14197,5,1,both,Tomato Paste,9,9,5.6,both
32404855,3421081,3421081,2977660,206209,prior,13,1,12,7.0,False,38730,6,0,both,Brownie Crunch High Protein Bar,3,19,5.9,both
32404856,3421081,3421081,2977660,206209,prior,13,1,12,7.0,False,31477,7,0,both,High Protein Bar Chunky Peanut Butter,3,19,4.2,both
32404857,3421081,3421081,2977660,206209,prior,13,1,12,7.0,False,6567,8,0,both,Chocolate Peanut Butter Protein Bar,3,19,4.9,both
32404858,3421081,3421081,2977660,206209,prior,13,1,12,7.0,False,22920,9,0,both,Roasted & Salted Shelled Pistachios,117,19,1.7,both

####  Observation: I couldn't use indicator=True in the merge test above because the orders_products_combined DataFrame already contains a _merge column. Instead, I used indicator='Match'.

In [12]:
# Drop the merge column in the orders_products_combined df
orders_products_combined = orders_products_combined.drop(['_merge'], axis=1)

In [13]:
#check the output 
orders_products_combined.head()

,Unnamed: 0.1,Unnamed: 0,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,First_order,product_id,add_to_cart_order,reordered
0,0,0,2539329,1,prior,1,2,8,NaN,True,196,1,0
1,0,0,2539329,1,prior,1,2,8,NaN,True,14084,2,0
2,0,0,2539329,1,prior,1,2,8,NaN,True,12427,3,0
3,0,0,2539329,1,prior,1,2,8,NaN,True,26088,4,0
4,0,0,2539329,1,prior,1,2,8,NaN,True,26405,5,0

In [14]:
# Merge updated DataFrame (permanently)
df_orders_products_combined = df_products_checked.merge(orders_products_combined, on = 'product_id', indicator = True)

In [15]:
# Check the output
df_orders_products_combined.head()

,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0.1,Unnamed: 0,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,First_order,add_to_cart_order,reordered,_merge
0,1,Chocolate Sandwich Cookies,61,19,5.8,1987,1987,3139998,138,prior,28,6,11,3.0,False,5,0,both
1,1,Chocolate Sandwich Cookies,61,19,5.8,1989,1989,1977647,138,prior,30,6,17,20.0,False,1,1,both
2,1,Chocolate Sandwich Cookies,61,19,5.8,11433,11433,389851,709,prior,2,0,21,6.0,False,20,0,both
3,1,Chocolate Sandwich Cookies,61,19,5.8,12198,12198,652770,764,prior,1,3,13,NaN,True,10,0,both
4,1,Chocolate Sandwich Cookies,61,19,5.8,12200,12200,1813452,764,prior,3,4,17,9.0,False,11,1,both

In [16]:
# Check the shape
df_orders_products_combined.shape

(32404859, 18)

In [17]:
# Checking the result of merge using the merge flag
df_orders_products_combined['_merge'].value_counts()

_merge
both          32404859
left_only            0
right_only           0
Name: count, dtype: int64

In [18]:
# Export data to pkl
df_orders_products_combined.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'ords_prods_merge.pkl'))

In [19]:
df_orders_products_combined.shape

(32404859, 18)