# Customer Data Integration

## Table of Contents
#### 1. Importing libraries and Customers data
#### 2. Data Wrangling - Customers data
#### 3. Data Consistency Checks - Customers data
#### 4. Combining the Customers data with the rest of the prepared Instacart data

## 1. Importing libraries and Customers data

In [1]:
# Import libraries

import pandas as pd
import numpy as np
import os

In [2]:
# Main path
path = r'/Users/helenarobalinho/Desktop/Data Analytics/2. Data Immersion/Achievement 4 - Python Fundamentals for Data Analysts/03-2026 Instacart Basket Analysis'

In [3]:
# Importing the customer data
customers = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'customers.csv'))

In [4]:
# Checking the size
customers.shape

(206209, 10)

## 2. Data Wrangling - Customers data

In [5]:
# Checking the content
customers.head()

,user_id,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [6]:
# Renaming columns to fix inconsistencies:

customers.rename (columns = {'First Name' : 'first_name', 'Surnam' : 'surname', 'Gender' : 'gender', 'STATE' : 'state', 'Age' : 'age', 'n_dependants' : 'n_dependents'}, inplace = True)

In [7]:
# Checking the output:
customers.head()

,user_id,first_name,surname,gender,state,age,date_joined,n_dependents,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

Now the variables names are correct and consistent by using the same alphabetical case.

I'm not dropping any columns, I believe they're relevant to the analysis.

In [8]:
# Inspecting the df with some descriptive statistics:
customers.describe()

             user_id            age   n_dependents         income
count  206209.000000  206209.000000  206209.000000  206209.000000
mean   103105.000000      49.501646       1.499823   94632.852548
std     59527.555167      18.480962       1.118433   42473.786988
min         1.000000      18.000000       0.000000   25903.000000
25%     51553.000000      33.000000       0.000000   59874.000000
50%    103105.000000      49.000000       1.000000   93547.000000
75%    154657.000000      66.000000       3.000000  124244.000000
max    206209.000000      81.000000       3.000000  593901.000000

These stats seem reasonable.

In [9]:
# Let's check data types of each column:
customers.dtypes

user_id          int64
first_name      object
surname         object
gender          object
state           object
age              int64
date_joined     object
n_dependents     int64
fam_status      object
income           int64
dtype: object

Data type of 'user_id' variable is integer. There will be no need to calculate stats for this variable, as it is an identifier. I'll change it to a string data type.

In [10]:
# Changing data type of 'user_id' column to string

customers['user_id'] = customers['user_id'].astype('str')

In [11]:
# Checking the output:

customers['user_id'].dtype

dtype('O')

## 3. Data Consistency Checks - Customers data

Mixed-type data

In [12]:
# Checking whether the dataframe contains any mixed-type columns:

for col in customers.columns.tolist():
    weird = (customers[[col]].map(type) != customers
             [[col]].iloc[0].apply(type)).any(axis = 1)
    if len(customers[weird]) > 0:
        print(col)

first_name

In [13]:
# Fixing the mixed-type data in the 'first_name' column:

customers['first_name'] = customers ['first_name'].astype('str')

In [14]:
# Checking the output:

customers['first_name'].dtype

dtype('O')

In [15]:
# A second check:

for col in customers.columns.tolist():
    weird = (customers[[col]].map(type) != customers
             [[col]].iloc[0].apply(type)).any(axis = 1)
    if len(customers[weird]) > 0:
        print(col)

In [16]:
# All good now.

Missing Values

In [17]:
# Finding any possible missing values:

customers.isnull().sum()

user_id         0
first_name      0
surname         0
gender          0
state           0
age             0
date_joined     0
n_dependents    0
fam_status      0
income          0
dtype: int64

There are no missing values to fix.

Duplicated Data

In [18]:
# Finding any possible duplicated rows:

customers_dups = customers [customers.duplicated()]

In [19]:
# Checking the output:

customers_dups

Empty DataFrame
Columns: [user_id, first_name, surname, gender, state, age, date_joined, n_dependents, fam_status, income]
Index: []

There is no duplicated data to fix.

## 4. Combining the Customers data with the rest of the prepared Instacart data

In [20]:
# Importing the prepared dataframe 'orders_products_merged_grouped'

ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merged_grouped.pkl'))

In [21]:
# Checking the output

ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,...,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,avg_product_price,spending_flag,median_days_between_orders,order_frequency_flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,Mid-range product,Regularly busy,Regular days,Most orders,32,Regular customer,6.935811,Low spender,8.0,Frequent customer
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,Mid-range product,Regularly busy,Regular days,Average orders,32,Regular customer,6.935811,Low spender,8.0,Frequent customer
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer,7.930208,Low spender,8.0,Frequent customer
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,Mid-range product,Regularly busy,Slowest days,Most orders,3,New customer,4.972414,Low spender,9.0,Frequent customer
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,Mid-range product,Least busy,Slowest days,Average orders,3,New customer,4.972414,Low spender,9.0,Frequent customer

In [22]:
# Checking the size

ords_prods_merge.shape

(32404859, 25)

Key-column to merge the 2 dataframes: 'user_id'

In [23]:
# Making sure the data type matches the one of the customers df

ords_prods_merge['user_id'].dtype

dtype('int64')

In [24]:
# Converting the data type to string:

ords_prods_merge['user_id'] = ords_prods_merge['user_id'].astype('str')

In [25]:
# Checking results:

ords_prods_merge['user_id'].dtype

dtype('O')

Checking unique values in the user_id column in both dataframes

In [26]:
# Checking unique values in the user_id column (ords_prods_merge)

ords_prods_merge['user_id'].nunique()

206209

In [27]:
# Checking unique values in the user_id column (customers)

customers['user_id'].nunique()

206209

We have the same amount of unique values and the same data type, we can now merge both dataframes by the shared key_column.

In [28]:
# Merging test: the 'outer' merge will combine all the observations and show the real merge rate

merge_test = pd.merge (ords_prods_merge, customers, on = 'user_id', how = 'outer', indicator = 'merging_status')

In [29]:
# Let's verify the merging results:

merge_test ['merging_status'].value_counts()

merging_status
both          32404859
left_only            0
right_only           0
Name: count, dtype: int64

In [30]:
# The outcome is a full match, so we can move to a permanent merge:

final_merged = ords_prods_merge.merge(customers, on = 'user_id', how = 'inner')

In [31]:
# Checking the output

final_merged.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,...,order_frequency_flag,first_name,surname,gender,state,age,date_joined,n_dependents,fam_status,income
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,Frequent customer,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,Frequent customer,Charles,Cox,Male,Minnesota,81,8/1/2019,1,married,49620
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,Frequent customer,Deborah,Glass,Female,Vermont,66,6/16/2018,2,married,158302
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,Frequent customer,Heather,Myers,Female,Wisconsin,40,2/9/2020,3,married,31308
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,Frequent customer,Heather,Myers,Female,Wisconsin,40,2/9/2020,3,married,31308

In [32]:
# Checking the size:

final_merged.shape

(32404859, 34)

## Exporting final_merged dataframe

In [33]:
# Exporting the final_merged df:

final_merged.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'final_merged.pkl'))